name: Build LaTeX and Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    strategy:
      matrix:
        language: ['english', 'german']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Git LFS pull
        run: git lfs pull
      - name: Set Language
        run: |
          echo "\def\mylanguage{${{ matrix.language }}}" > src/selected_language.tex
          echo "" >> src/selected_language.tex
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
          latexmk_use_xelatex: true
          args: "-synctex=1 -interaction=nonstopmode -file-line-error"
          post_compile: >
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=vincent_cv_${{ matrix.language }}.pdf main.pdf
      - name: Upload artifacts for release
        uses: actions/upload-artifact@v2
        with:
          name: vincent_cv_${{ matrix.language }}
          path: vincent_cv_${{ matrix.language }}.pdf
      - name: Upload artifacts to fileserver
        run: |
          curl -X POST -H "X-API-Key: ${{ secrets.FILE_SERVER_API_KEY }}" -F "file=@vincent_cv_${{ matrix.language }}.pdf" ${{ secrets.FILE_SERVER_URL }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
      - name: Download English artifact
        uses: actions/download-artifact@v2
        with:
          name: vincent_cv_english
          path: .
      - name: Download German artifact
        uses: actions/download-artifact@v2
        with:
          name: vincent_cv_german
          path: .
      - name: Upload Release Asset
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          args: '*.pdf'
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
