name: Build LaTeX and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          args: "-synctex=1 -interaction=nonstopmode -file-line-error"
          extra_fonts: |
            ./assets/fonts/Roboto/Roboto-*.ttf
            ./assets/fonts/Panton-BlackCaps.otf
            ./assets/fonts/Acumin-BdPro.otf
          post_compile: >
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=vincent_cv.pdf main.pdf
      - name: Create release and upload PDF
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'vincent_cv.pdf'
